// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Avatar struct {
	Avatar *string `json:"avatar"`
}

type GantActivityInput struct {
	ActualBudget     *string                     `json:"actualBudget"`
	ActualEndDate    *string                     `json:"actualEndDate"`
	ActualStartDate  *string                     `json:"actualStartDate"`
	Assignees        []*GanttAssignedUpdateInput `json:"assignees"`
	Dependency       *int                        `json:"dependency"`
	Description      *string                     `json:"description"`
	ID               *int                        `json:"id"`
	Name             string                      `json:"name"`
	PlannedBudget    *string                     `json:"plannedBudget"`
	PlannedEndDate   string                      `json:"plannedEndDate"`
	PlannedStartDate string                      `json:"plannedStartDate"`
	Ganttstate       *int                        `json:"Ganttstate"`
	Gantttask        int                         `json:"Gantttask"`
}

type GantActivityUpdateInput struct {
	ActualBudget     *string                     `json:"actualBudget"`
	ActualEndDate    *string                     `json:"actualEndDate"`
	ActualStartDate  *string                     `json:"actualStartDate"`
	Assignees        []*GanttAssignedUpdateInput `json:"assignees"`
	Dependency       *int                        `json:"dependency"`
	Description      *string                     `json:"description"`
	ID               *int                        `json:"id"`
	Name             string                      `json:"name"`
	PlannedBudget    *string                     `json:"plannedBudget"`
	PlannedEndDate   string                      `json:"plannedEndDate"`
	PlannedStartDate string                      `json:"plannedStartDate"`
	Ganttstate       *int                        `json:"Ganttstate"`
	Gantttask        *int                        `json:"Gantttask"`
}

type GanttAssignedInput struct {
	Ganttactivity int  `json:"Ganttactivity"`
	ID            *int `json:"id"`
	User          int  `json:"user"`
}

type GanttAssignedToMe struct {
	ActualStartDate *string `json:"actualStartDate"`
	Dependency      *int    `json:"dependency"`
	ID              *int    `json:"id"`
	Name            string  `json:"name"`
	PlannedEndDate  string  `json:"plannedEndDate"`
	Ganttproject    *string `json:"Ganttproject"`
	GanttprojectID  *int    `json:"GanttprojectId"`
	Ganttstate      *int    `json:"Ganttstate"`
	Gantttask       int     `json:"Gantttask"`
}

type GanttAssignedUpdateInput struct {
	Ganttactivity *int `json:"Ganttactivity"`
	ID            *int `json:"id"`
	User          int  `json:"user"`
}

type GanttCommentInput struct {
	Ganttactivity int     `json:"Ganttactivity"`
	Author        *int    `json:"author"`
	CreatedAt     *string `json:"createdAt"`
	ID            *int    `json:"id"`
	Text          string  `json:"text"`
	UpdatedAt     *string `json:"updatedAt"`
}

type GanttCommentOnlyChangeTextInput struct {
	Ganttactivity *int    `json:"Ganttactivity"`
	Author        *int    `json:"author"`
	CreatedAt     *string `json:"createdAt"`
	ID            *int    `json:"id"`
	Text          string  `json:"text"`
	UpdatedAt     *string `json:"updatedAt"`
}

type GanttProjectInput struct {
	ActualEndDate       *string `json:"actualEndDate"`
	ActualStartDate     *string `json:"actualStartDate"`
	Description         *string `json:"description"`
	ID                  *int    `json:"id"`
	Name                string  `json:"name"`
	PlannedEndDate      string  `json:"plannedEndDate"`
	PlannedStartDate    string  `json:"plannedStartDate"`
	GanttprojectManager *int    `json:"GanttprojectManager"`
}

type GanttRoleInput struct {
	ID           *int   `json:"id"`
	Name         string `json:"name"`
	Ganttproject int    `json:"Ganttproject"`
}

type GanttStateInput struct {
	ID           *int   `json:"id"`
	Name         string `json:"name"`
	Ganttproject int    `json:"Ganttproject"`
}

type GanttStateUpdateInput struct {
	ID           *int   `json:"id"`
	Name         string `json:"name"`
	Ganttproject *int   `json:"Ganttproject"`
}

type GanttTaskInput struct {
	ActualBudget     *string `json:"actualBudget"`
	ActualEndDate    *string `json:"actualEndDate"`
	ActualStartDate  *string `json:"actualStartDate"`
	Description      *string `json:"description"`
	ID               *int    `json:"id"`
	Name             string  `json:"name"`
	PlannedBudget    *string `json:"plannedBudget"`
	PlannedEndDate   string  `json:"plannedEndDate"`
	PlannedStartDate string  `json:"plannedStartDate"`
	Ganttproject     int     `json:"Ganttproject"`
}

type GanttTaskUpdateInput struct {
	ActualBudget     *string `json:"actualBudget"`
	ActualEndDate    *string `json:"actualEndDate"`
	ActualStartDate  *string `json:"actualStartDate"`
	Description      *string `json:"description"`
	ID               *int    `json:"id"`
	Name             string  `json:"name"`
	PlannedBudget    *string `json:"plannedBudget"`
	PlannedEndDate   string  `json:"plannedEndDate"`
	PlannedStartDate string  `json:"plannedStartDate"`
	Ganttproject     *int    `json:"Ganttproject"`
}

type GanttTeamInput struct {
	ID           *int   `json:"id"`
	Name         string `json:"name"`
	Ganttproject int    `json:"Ganttproject"`
}

type GanttTeamMember struct {
	ID        *int `json:"id"`
	Ganttrole int  `json:"Ganttrole"`
	Ganttteam int  `json:"Ganttteam"`
	User      int  `json:"user"`
}

type GanttTeamMemberGetInput struct {
	ID        *int `json:"id"`
	Ganttrole int  `json:"Ganttrole"`
	Ganttteam int  `json:"Ganttteam"`
	User      *int `json:"user"`
}

type GanttTeamMemberInput struct {
	ID        *int `json:"id"`
	Ganttrole int  `json:"Ganttrole"`
	Ganttteam int  `json:"Ganttteam"`
	User      int  `json:"user"`
}

type User struct {
	Avatar    *string `json:"avatar"`
	FirstName *string `json:"firstName"`
	ID        *int    `json:"id"`
	LastName  *string `json:"lastName"`
	Username  *string `json:"username"`
}

type UserInput struct {
	Avatar    *string `json:"avatar"`
	Email     *string `json:"email"`
	FirstName *string `json:"firstName"`
	ID        *int    `json:"id"`
	LastName  *string `json:"lastName"`
	// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
	Username *string `json:"username"`
}
