// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GanttTeamMember struct {
	ID   *int `json:"id"`
	Role int  `json:"role"`
	Team int  `json:"team"`
	User int  `json:"user"`
}
